# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maknoon < Formula
  desc "Premier Post-Quantum Security Suite: Hybrid HPKE (ML-KEM + X25519) encryption."
  homepage "https://github.com/al-Zamakhshari/maknoon"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.2.0/maknoon_1.2.0_darwin_amd64.tar.gz"
      sha256 "30c51556eef642a59e5d376ea9378360311796cc464ff2846cd047ecf4ad4aea"

      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.2.0/maknoon_1.2.0_darwin_arm64.tar.gz"
      sha256 "9bdacdf63d02ac6849b551c4f8f986bc4a11df5a79bb8814248b50ae8e0b3e7e"

      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.2.0/maknoon_1.2.0_linux_amd64.tar.gz"
      sha256 "ace78469f03e218fbab4e0c1b8164afd3b4c474c2fc05b8a848364e36c428bac"
      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v1.2.0/maknoon_1.2.0_linux_arm64.tar.gz"
      sha256 "56a21cd02a64c67bf3ca0a619666a9ef0d724acc98b82a515efd12560db7f183"
      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
  end

  test do
    system "#{bin}/maknoon --version"
  end
end
