# This file was generated by GoReleaser. DO NOT EDIT.
cask "maknoon" do
  version "1.1.73"

  on_macos do
    on_intel do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_darwin_amd64.tar.gz"
      sha256 "7e4e71319ff34263c9e881c97a0d5ba305c70e40daa34eaf53a4f889afbcf2aa"
    end
    on_arm do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_darwin_arm64.tar.gz"
      sha256 "fb61784de619248a22526bce75e27e9165fc78c7fbaca3b24916f29d80d25403"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_linux_amd64.tar.gz"
      sha256 "cdd3e523d298ba83f7a0fdb94bb87f7e5f82e7913e30d65ae5e4d6b908732a0c"
    end
    on_arm do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_linux_arm64.tar.gz"
      sha256 "67a3ba3b8c8a6430547be3cde2e657206306743029cd7e19b25d667c576fdcd4"
    end
  end

  name "maknoon"
  desc "Versatile, ultra-efficient Post-Quantum CLI encryption tool."
  homepage "https://github.com/al-Zamakhshari/maknoon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "maknoon"
  manpage "maknoon.1"

  # No zap stanza required

end
