# This file was generated by GoReleaser. DO NOT EDIT.
cask "maknoon" do
  version "1.1.57"

  on_macos do
    on_intel do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_darwin_amd64.tar.gz"
      sha256 "e78fe23be216c5b7f49994a1e5b6ea84506106183868d2d0a9ca101e5fbbe368"
    end
    on_arm do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_darwin_arm64.tar.gz"
      sha256 "0b8197291bf0db96be82e913e48f4c8e78f9d9316b1d9ec2ba365fbc1def452d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_linux_amd64.tar.gz"
      sha256 "183d1ca83e31b887e65b246f9c7e626652e2ce8150e029b6166a7e52d649dd27"
    end
    on_arm do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_linux_arm64.tar.gz"
      sha256 "57d18c55342966aa90a49b9aae765ae38cac6fdfdc8bf1ca5540c2615d2f6b63"
    end
  end

  name "maknoon"
  desc "Versatile, ultra-efficient Post-Quantum CLI encryption tool."
  homepage "https://github.com/al-Zamakhshari/maknoon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "maknoon"
  manpage "maknoon.1"

  # No zap stanza required

end
