# This file was generated by GoReleaser. DO NOT EDIT.
cask "maknoon" do
  version "1.1.70"

  on_macos do
    on_intel do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_darwin_amd64.tar.gz"
      sha256 "0dab05d92d75880cc98f866ac608beae18360b3eefba8d660be25d05953f5550"
    end
    on_arm do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_darwin_arm64.tar.gz"
      sha256 "6a87414164f357bd170998a9fa4268def6cdf40254198c9e57290761eeea60f5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_linux_amd64.tar.gz"
      sha256 "8468a720798c46b34b6cb4c0ad7a1fc68fd1262b751bf4dfdfa7b154bc3f7425"
    end
    on_arm do
      url "https://github.com/al-Zamakhshari/maknoon/releases/download/v#{version}/maknoon_#{version}_linux_arm64.tar.gz"
      sha256 "d9205f3941043f731be9bd9040e9e31256f3403e62ea38679fd3564e7582751b"
    end
  end

  name "maknoon"
  desc "Versatile, ultra-efficient Post-Quantum CLI encryption tool."
  homepage "https://github.com/al-Zamakhshari/maknoon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "maknoon"
  manpage "maknoon.1"

  # No zap stanza required

end
