# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maknoon < Formula
  desc "Versatile, ultra-efficient Post-Quantum CLI encryption tool with streaming directory support and memory hygiene."
  homepage "https://github.com/a-khallaf/maknoon"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/a-khallaf/maknoon/releases/download/v1.0.4/maknoon_1.0.4_darwin_amd64.tar.gz"
      sha256 "c25153d2ea3c4ca238d65fd7e97de748bbc159cab7ee89495cc17d9646bd93a7"

      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/a-khallaf/maknoon/releases/download/v1.0.4/maknoon_1.0.4_darwin_arm64.tar.gz"
      sha256 "6adf30a78ebd28b4843661aafb3663e5da66f01f8029cadba6310051f5d9624d"

      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/a-khallaf/maknoon/releases/download/v1.0.4/maknoon_1.0.4_linux_amd64.tar.gz"
      sha256 "08d267eb546cc56fe887898cb1059e2ebd17676e63035fb7c0f965fad4f44906"
      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/a-khallaf/maknoon/releases/download/v1.0.4/maknoon_1.0.4_linux_arm64.tar.gz"
      sha256 "d4c9d56085e2be466601b243b93b1a55cedf30ad29a0728d70b79367f57e058e"
      define_method(:install) do
        bin.install "maknoon"
        man1.install "maknoon.1"
      end
    end
  end

  test do
    system "#{bin}/maknoon --version"
  end
end
